// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectTallify.Models;

#nullable disable

namespace ProjectTallify.Migrations
{
    [DbContext(typeof(TallifyDbContext))]
    [Migration("20251209185802_MakeAuditLogEventIdNullable")]
    partial class MakeAuditLogEventIdNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ProjectTallify.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Details")
                        .HasColumnType("longtext");

                    b.Property<int?>("EventId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserRole")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("ProjectTallify.Models.ComputedRoundScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("ComputedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ContestantId")
                        .HasColumnType("int");

                    b.Property<int?>("CriteriaId")
                        .HasColumnType("int");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<decimal>("Rank")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("RoundId")
                        .HasColumnType("int");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("ContestantId");

                    b.HasIndex("CriteriaId");

                    b.HasIndex("EventId");

                    b.HasIndex("RoundId");

                    b.ToTable("ComputedRoundScores");
                });

            modelBuilder.Entity("ProjectTallify.Models.Contestant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Organization")
                        .HasColumnType("longtext");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("Contestants");
                });

            modelBuilder.Entity("ProjectTallify.Models.Criteria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("DerivedFromRoundId")
                        .HasColumnType("int");

                    b.Property<int?>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDerived")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("MaxPoints")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("MinPoints")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("RoundId")
                        .HasColumnType("int");

                    b.Property<decimal>("WeightPercent")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("DerivedFromRoundId");

                    b.HasIndex("EventId");

                    b.HasIndex("RoundId");

                    b.ToTable("Criterias");
                });

            modelBuilder.Entity("ProjectTallify.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AccessCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AccessJson")
                        .HasColumnType("longtext");

                    b.Property<string>("AveragingJson")
                        .HasColumnType("longtext");

                    b.Property<string>("ContestantsJson")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HeaderImage")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PointingJson")
                        .HasColumnType("longtext");

                    b.Property<string>("RoundsJson")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ThemeColor")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("ProjectTallify.Models.Judge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateVerified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAccessSent")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsInviteSent")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Pin")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("VerificationToken")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("Judges");
                });

            modelBuilder.Entity("ProjectTallify.Models.NotificationLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("NotificationLogs");
                });

            modelBuilder.Entity("ProjectTallify.Models.OrwPointRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("PointsPerBonus")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("PointsPerCorrect")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("PointsPerViolation")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("PointsPerWrong")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("RoundId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoundId")
                        .IsUnique();

                    b.ToTable("OrwPointRules");
                });

            modelBuilder.Entity("ProjectTallify.Models.OverallScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("ComputedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ContestantId")
                        .HasColumnType("int");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<decimal>("Rank")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("ContestantId");

                    b.HasIndex("EventId");

                    b.ToTable("OverallScores");
                });

            modelBuilder.Entity("ProjectTallify.Models.Round", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("RoundType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("Rounds");
                });

            modelBuilder.Entity("ProjectTallify.Models.Score", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ContestantId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CriteriaId")
                        .HasColumnType("int");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int?>("JudgeId")
                        .HasColumnType("int");

                    b.Property<int>("RoundId")
                        .HasColumnType("int");

                    b.Property<int?>("ScorerId")
                        .HasColumnType("int");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("ContestantId");

                    b.HasIndex("CriteriaId");

                    b.HasIndex("EventId");

                    b.HasIndex("JudgeId");

                    b.HasIndex("RoundId");

                    b.HasIndex("ScorerId");

                    b.ToTable("Scores");
                });

            modelBuilder.Entity("ProjectTallify.Models.Scorer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AssignedContestantIds")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Pin")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("Scorers");
                });

            modelBuilder.Entity("ProjectTallify.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("EmailVerificationToken")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("EmailVerificationTokenExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("EnableNotifications")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OrganizationPhotoPath")
                        .HasColumnType("longtext");

                    b.Property<string>("OrganizationSubtitle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("PasswordResetTokenExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ProfilePhotoPath")
                        .HasColumnType("longtext");

                    b.Property<string>("RememberMeToken")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("RememberMeTokenExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ThemeColor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ProjectTallify.Models.AuditLog", b =>
                {
                    b.HasOne("ProjectTallify.Models.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId");

                    b.HasOne("ProjectTallify.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProjectTallify.Models.ComputedRoundScore", b =>
                {
                    b.HasOne("ProjectTallify.Models.Contestant", "Contestant")
                        .WithMany("ComputedRoundScores")
                        .HasForeignKey("ContestantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectTallify.Models.Criteria", "Criteria")
                        .WithMany("ComputedRoundScores")
                        .HasForeignKey("CriteriaId");

                    b.HasOne("ProjectTallify.Models.Event", "Event")
                        .WithMany("ComputedRoundScores")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectTallify.Models.Round", "Round")
                        .WithMany("ComputedRoundScores")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contestant");

                    b.Navigation("Criteria");

                    b.Navigation("Event");

                    b.Navigation("Round");
                });

            modelBuilder.Entity("ProjectTallify.Models.Contestant", b =>
                {
                    b.HasOne("ProjectTallify.Models.Event", "Event")
                        .WithMany("Contestants")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("ProjectTallify.Models.Criteria", b =>
                {
                    b.HasOne("ProjectTallify.Models.Round", "DerivedFromRound")
                        .WithMany()
                        .HasForeignKey("DerivedFromRoundId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProjectTallify.Models.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectTallify.Models.Round", "Round")
                        .WithMany("Criterias")
                        .HasForeignKey("RoundId");

                    b.Navigation("DerivedFromRound");

                    b.Navigation("Event");

                    b.Navigation("Round");
                });

            modelBuilder.Entity("ProjectTallify.Models.Event", b =>
                {
                    b.HasOne("ProjectTallify.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProjectTallify.Models.Judge", b =>
                {
                    b.HasOne("ProjectTallify.Models.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("ProjectTallify.Models.NotificationLog", b =>
                {
                    b.HasOne("ProjectTallify.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProjectTallify.Models.OrwPointRule", b =>
                {
                    b.HasOne("ProjectTallify.Models.Round", "Round")
                        .WithOne("OrwPointRule")
                        .HasForeignKey("ProjectTallify.Models.OrwPointRule", "RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Round");
                });

            modelBuilder.Entity("ProjectTallify.Models.OverallScore", b =>
                {
                    b.HasOne("ProjectTallify.Models.Contestant", "Contestant")
                        .WithMany("OverallScores")
                        .HasForeignKey("ContestantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectTallify.Models.Event", "Event")
                        .WithMany("OverallScores")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contestant");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("ProjectTallify.Models.Round", b =>
                {
                    b.HasOne("ProjectTallify.Models.Event", "Event")
                        .WithMany("Rounds")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("ProjectTallify.Models.Score", b =>
                {
                    b.HasOne("ProjectTallify.Models.Contestant", "Contestant")
                        .WithMany("Scores")
                        .HasForeignKey("ContestantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectTallify.Models.Criteria", "Criteria")
                        .WithMany("Scores")
                        .HasForeignKey("CriteriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectTallify.Models.Event", "Event")
                        .WithMany("Scores")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectTallify.Models.Judge", "Judge")
                        .WithMany("Scores")
                        .HasForeignKey("JudgeId");

                    b.HasOne("ProjectTallify.Models.Round", "Round")
                        .WithMany("Scores")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectTallify.Models.Scorer", "Scorer")
                        .WithMany("Scores")
                        .HasForeignKey("ScorerId");

                    b.Navigation("Contestant");

                    b.Navigation("Criteria");

                    b.Navigation("Event");

                    b.Navigation("Judge");

                    b.Navigation("Round");

                    b.Navigation("Scorer");
                });

            modelBuilder.Entity("ProjectTallify.Models.Scorer", b =>
                {
                    b.HasOne("ProjectTallify.Models.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("ProjectTallify.Models.Contestant", b =>
                {
                    b.Navigation("ComputedRoundScores");

                    b.Navigation("OverallScores");

                    b.Navigation("Scores");
                });

            modelBuilder.Entity("ProjectTallify.Models.Criteria", b =>
                {
                    b.Navigation("ComputedRoundScores");

                    b.Navigation("Scores");
                });

            modelBuilder.Entity("ProjectTallify.Models.Event", b =>
                {
                    b.Navigation("ComputedRoundScores");

                    b.Navigation("Contestants");

                    b.Navigation("OverallScores");

                    b.Navigation("Rounds");

                    b.Navigation("Scores");
                });

            modelBuilder.Entity("ProjectTallify.Models.Judge", b =>
                {
                    b.Navigation("Scores");
                });

            modelBuilder.Entity("ProjectTallify.Models.Round", b =>
                {
                    b.Navigation("ComputedRoundScores");

                    b.Navigation("Criterias");

                    b.Navigation("OrwPointRule");

                    b.Navigation("Scores");
                });

            modelBuilder.Entity("ProjectTallify.Models.Scorer", b =>
                {
                    b.Navigation("Scores");
                });
#pragma warning restore 612, 618
        }
    }
}
